# Generated by Django 4.1.1 on 2022-11-14 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_ram', models.IntegerField(default=2)),
                ('phone_number', models.CharField(max_length=10)),
                ('club_department', models.CharField(choices=[('web development', 'web developmnet'), ('app development', 'app develpment'), ('web design', 'web design'), ('others', 'others')], max_length=100)),
                ('department', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
