# Generated by Django 4.1.1 on 2022-11-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='admins')),
                ('twittter', models.CharField(max_length=300)),
                ('whatsapp', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('experties_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
