# Generated by Django 4.1.1 on 2022-11-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_picture',
            field=models.ImageField(default='system/Media/admins/default.png', upload_to='idcard'),
        ),
    ]
