# Generated by Django 3.2.16 on 2022-12-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_profile_card_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='icons')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_picture',
            field=models.ImageField(default='default.png', upload_to='idcard'),
        ),
    ]
